pipeline {
    agent any
        
    }
    stages {
        stage('Build') {
            steps {
                withMaven(maven:'MAVEN_HOME'){
                    sh 'mvn -B -DskipTests clean package' }
                
            }
        }
        stage('Test') {
            steps {
                withMaven(maven:'MAVEN_HOME') {
                sh 'mvn test'
                }
                }
        }
}
